### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by AilenPalma**
modificaciones css

### CODE REVIEW

**Comment by AilenPalma** [comment]
1

**Comment by AilenPalma** [comment]
1

**Review by AilenPalma — COMMENTED** [review]
modificaciones css

**Review by Imran-imtiaz48 — COMMENTED** [review]
Review Comments
1.	Grid Layout:
o	The .Motivation grid is structured well for a two-column layout with equal spacing. Using 1fr 1fr is a clean way to achieve equal column widths.
2.	Vertical Centering:
o	The align-items: center ensures proper vertical alignment. Combined with height: 100vh, it achieves a full-screen layout effectively.
3.	Background Styling:
o	background-image and background-size: cover work well to ensure the image spans the entire section, giving it a polished look.
o	Consider using a background-position: center to ensure the image is aligned correctly on all screen sizes.
4.	Text Styling:
o	The .text-box has a nice touch with the shadow effects, adding a dynamic and vibrant feel to the text. However, be cautious with overusing multiple colors in shadows as it might be distracting on some screens.
5.	Responsive Design:
o	The padding: 20px in .titile, .text-container is a thoughtful addition for mobile responsiveness.
o	To further enhance responsiveness, consider adding a media query for smaller screens. For instance:
o	@media (max-width: 768px) {
o	  .Motivation {
o	    grid-template-columns: 1fr; /* Stack the columns on smaller devices */
o	    gap: 10px;
o	  }
o	  .text-box {
o	    font-size: large; /* Adjust font size for readability */
o	  }
o	}
6.	Typography:
o	Using 'text-p' and 'title' for fonts adds customization. Ensure the font files are properly linked and fallback fonts are provided, e.g.: 
o	font-family: 'title', Arial, sans-serif;
7.	Performance:
o	If the image file is large, consider optimizing it for faster loading. You might also want to preload it using <link rel="preload" href="path-to-image" as="image"> in your HTML.
8.	Redundant Semi-Colons:
o	The .titile class has an extra semi-colon after font-family and font-size. While harmless, cleaning these up improves readability and consistency.
________________________________________
Actionable Suggestions
•	Add a fallback font for better cross-browser support.
•	Use media queries for better responsiveness across different devices.
•	Optimize the background image and consider lazy loading if applicable.
•	Clean up redundant semi-colons in .titile.

**Pull request merged**
